#!/usr/bin/env python3
"""
测试报告生成器 —— 从 Claude 收集的结果 JSON 生成报告。

子命令:
  generate  --dir PROJECT_DIR --data RESULTS_JSON  生成 report.json + summary.md
  view      --dir PROJECT_DIR [--run RUN_ID]       查看报告内容
  list      --dir PROJECT_DIR                      列出所有历史报告
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime


def generate(project_dir: str, data: dict) -> dict:
    """从结果 JSON 生成 report.json + summary.md"""
    project_dir = os.path.abspath(project_dir)

    run_id = data.get("run_id", datetime.now().strftime("%Y%m%d_%H%M%S"))
    report_dir = os.path.join(project_dir, "reports", run_id)
    os.makedirs(report_dir, exist_ok=True)

    # 补充统计信息
    tests = data.get("tests", [])
    total = len(tests)
    passed = sum(1 for t in tests if t.get("status") == "passed")
    failed = sum(1 for t in tests if t.get("status") == "failed")
    skipped = sum(1 for t in tests if t.get("status") == "skipped")

    report = {
        "run_id": run_id,
        "package": data.get("package", ""),
        "device": data.get("device", ""),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "total": total,
        "passed": passed,
        "failed": failed,
        "skipped": skipped,
        "pass_rate": round(passed / total * 100, 1) if total > 0 else 0,
        "tests": tests,
    }

    # 写入 report.json
    report_path = os.path.join(report_dir, "report.json")
    with open(report_path, "w") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)

    # 生成 summary.md
    summary = _render_summary(report)
    summary_path = os.path.join(report_dir, "summary.md")
    with open(summary_path, "w") as f:
        f.write(summary)

    return {
        "success": True,
        "run_id": run_id,
        "report_dir": report_dir,
        "report_json": report_path,
        "summary_md": summary_path,
        "total": total,
        "passed": passed,
        "failed": failed,
        "skipped": skipped,
    }


def _render_summary(report: dict) -> str:
    """渲染 Markdown 格式的测试报告摘要"""
    lines = [
        f"# 测试报告 {report['run_id']}",
        "",
        f"- **应用包名**: {report.get('package', 'N/A')}",
        f"- **设备**: {report.get('device', 'N/A')}",
        f"- **时间**: {report.get('timestamp', 'N/A')}",
        "",
        "## 总览",
        "",
        f"| 总计 | 通过 | 失败 | 跳过 | 通过率 |",
        f"|------|------|------|------|--------|",
        f"| {report['total']} | {report['passed']} | {report['failed']} | {report.get('skipped', 0)} | {report.get('pass_rate', 0)}% |",
        "",
        "## 测试详情",
        "",
    ]

    for test in report.get("tests", []):
        status_icon = {"passed": "PASS", "failed": "FAIL", "skipped": "SKIP"}.get(
            test.get("status", ""), "?")
        lines.append(f"### [{status_icon}] {test.get('id', 'unknown')}")
        lines.append("")

        steps = test.get("steps", [])
        if steps:
            lines.append("| 步骤 | 操作 | 结果 | 说明 |")
            lines.append("|------|------|------|------|")
            for i, step in enumerate(steps, 1):
                action = step.get("action", "")
                target = step.get("target", {})
                target_str = target.get("text", target.get("resource_id", ""))
                result = step.get("result", "")
                judgment = step.get("claude_judgment", "")
                lines.append(f"| {i} | {action} {target_str} | {result} | {judgment} |")
            lines.append("")

        if test.get("error"):
            lines.append(f"**错误**: {test['error']}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by droid-pilot*")

    return "\n".join(lines)


def view(project_dir: str, run_id: str = None) -> dict:
    """查看报告内容"""
    project_dir = os.path.abspath(project_dir)
    reports_dir = os.path.join(project_dir, "reports")

    if not run_id:
        # 查看最新报告
        if not os.path.isdir(reports_dir):
            return {"success": False, "error": "reports/ 目录不存在"}
        runs = sorted([d for d in os.listdir(reports_dir)
                       if os.path.isdir(os.path.join(reports_dir, d))])
        if not runs:
            return {"success": False, "error": "没有任何报告"}
        run_id = runs[-1]

    report_path = os.path.join(reports_dir, run_id, "report.json")
    summary_path = os.path.join(reports_dir, run_id, "summary.md")

    if not os.path.exists(report_path):
        return {"success": False, "error": f"报告不存在: {run_id}"}

    with open(report_path, "r") as f:
        report = json.load(f)

    summary = ""
    if os.path.exists(summary_path):
        with open(summary_path, "r") as f:
            summary = f.read()

    return {
        "success": True,
        "run_id": run_id,
        "report": report,
        "summary": summary,
    }


def list_reports(project_dir: str) -> dict:
    """列出所有历史报告"""
    project_dir = os.path.abspath(project_dir)
    reports_dir = os.path.join(project_dir, "reports")

    if not os.path.isdir(reports_dir):
        return {"success": True, "reports": []}

    reports = []
    for run_id in sorted(os.listdir(reports_dir), reverse=True):
        run_dir = os.path.join(reports_dir, run_id)
        if not os.path.isdir(run_dir):
            continue

        report_path = os.path.join(run_dir, "report.json")
        info = {"run_id": run_id}

        if os.path.exists(report_path):
            try:
                with open(report_path, "r") as f:
                    data = json.load(f)
                info.update({
                    "package": data.get("package", ""),
                    "timestamp": data.get("timestamp", ""),
                    "total": data.get("total", 0),
                    "passed": data.get("passed", 0),
                    "failed": data.get("failed", 0),
                    "pass_rate": data.get("pass_rate", 0),
                })
            except (json.JSONDecodeError, IOError):
                pass

        reports.append(info)

    return {
        "success": True,
        "report_count": len(reports),
        "reports": reports,
    }


def main():
    parser = argparse.ArgumentParser(description="测试报告生成器")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_gen = sub.add_parser("generate", help="生成测试报告")
    p_gen.add_argument("--dir", required=True, help="项目目录")
    p_gen.add_argument("--data", help="结果 JSON 字符串（不填则从 stdin 读）")

    p_view = sub.add_parser("view", help="查看报告")
    p_view.add_argument("--dir", required=True, help="项目目录")
    p_view.add_argument("--run", help="运行 ID（不填则查看最新）")

    p_list = sub.add_parser("list", help="列出所有报告")
    p_list.add_argument("--dir", required=True, help="项目目录")

    args = parser.parse_args()

    if args.cmd == "generate":
        raw = args.data if args.data else sys.stdin.read()
        data = json.loads(raw)
        result = generate(args.dir, data)
    elif args.cmd == "view":
        result = view(args.dir, getattr(args, "run", None))
    elif args.cmd == "list":
        result = list_reports(args.dir)

    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
